# Docker Compose file for DEVELOPMENT environment!
version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: "${DOCKER_ENV}_${DOCKER_APP_NAME}_app"
    volumes:
      - ./:/var/www
      - ./docker/app/entrypoint.sh:/scripts/entrypoint.sh
    environment:
      - APP_ENV=local
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    container_name: "${DOCKER_ENV}_${DOCKER_APP_NAME}_nginx"
    ports:
      - "14080:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: "${DOCKER_ENV}_${DOCKER_APP_NAME}_mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${DOCKER_ENV}_${DOCKER_APP_NAME}_phpmyadmin"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "14090:80"
    depends_on:
      - mysql

  redis:
    image: redis:latest
    container_name: "${DOCKER_ENV}_${DOCKER_APP_NAME}_redis"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: